// <auto-generated />
using System;
using Desafio.API.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Desafio.API.Migrations
{
    [DbContext(typeof(ContextoAPI))]
    partial class ContextoAPIModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("Desafio.Entidades.Entidades.Pessoa", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPF")
                        .HasColumnType("TEXT")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasMaxLength(150);

                    b.Property<string>("UF")
                        .HasColumnType("TEXT")
                        .HasMaxLength(2);

                    b.HasKey("Codigo");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("Desafio.Entidades.Entidades.Sessao", b =>
                {
                    b.Property<Guid>("Codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Ativo")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CodigoPessoa")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InicioSessao")
                        .HasColumnType("TEXT");

                    b.HasKey("Codigo");

                    b.HasIndex("CodigoPessoa");

                    b.ToTable("Sessao");
                });

            modelBuilder.Entity("Desafio.Entidades.Entidades.Sessao", b =>
                {
                    b.HasOne("Desafio.Entidades.Entidades.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("CodigoPessoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
